### ISSUE TITLE
parLapply style function that uses GPUs

### ISSUE THREAD

**Issue by antonysamuelb** [cdeterman/gpuR#113]
Can a parLapply style function be implemented for GPUs?

**Comment by cdeterman** [comment]
Possibly, the main issue is the external pointer thread safety well doing parallel operations.  This is noted in issue #24 and therefore I will close this issue and refer you to there.  As noted in there, the key is that you must return a normal, base R structure otherwise it will crash (as the external pointer will be lost).  As this is a 'reasonable' workaround at the moment (i.e. I haven't received enough interest) it is not a major priority although it is a major point on the roadmap.  I would love a collaborator to assist as my time I can dedicate to this package currently is limited.  Regardless, I unfortunately can't provide a solid estimate on when this will be implemented.
