### ISSUE TITLE
Eigenvalue/Eigenvector decomposition & Covariance Matrix calculation

### ISSUE THREAD

**Issue by erolbicero** [cdeterman/gpuR#3]
Hello,

Would it be possible to have eigenvalue & eigenvector decomposition implemented?  As well as covariance matrix calculations?
Thank you

**Comment by cdeterman** [comment]
This shouldn't be a problem as it is supported within ViennaCL.  Once I have the package with complete clean R CMD CHECK I will begin add this functionality.

**Comment by cdeterman** [comment]
@erolbicero It just occurred to me.  What covariance metrics are you interested in?  The Pearson metric is the simplest and I will implementing it soon, I'm just going back and forth about how I want the data handled on the card.  Spearman I still need to figure out an efficient way to rank elements so that will not become available until I do so (or some generous soul provides some code).  Other metrics?  

A quick point though, I will likely close this issue once I implement Pearson and eigen decomposition.  Probably will open a separate issue for additional covariance metrics.

A brief update otherwise, the eigenvalue and eigenvector methods are coming along nicely.  I am running tests with some updated gpuVector objects and should be pushing those updates soon (admittedly very hand-wavy but I can't guarantee timelines).

**Comment by erolbicero** [comment]
Hello @cdeterman,

Thanks for the update and for sharing your progress.  To answer your question, I think Pearson is sufficient for what I was hoping to do.

Down the line, perhaps some forms of robust covariance matrix estimation? Such as Minimum Covariance Determinant or Minimum Volume Ellipsoid?  I'd personally have to think about it, but as you stated, those can be separate 'issues'.

**Comment by cdeterman** [comment]
@erolbicero 

Eigen decomposition is not available for symmetric matrices (non-symmetric is not possible at the moment until we can implement of `complex` data type for OpenCL).  The syntax is identical to the base R syntax.  Please note the documentation that the eigenvalues and eigenvectors are not sorted.  I have made sure to include tests to make certain of equivalence to the results of R's `eigen` function.

Covariance is still in progress but feel free to test and explore.

**Comment by erolbicero** [comment]
@cdeterman, Eigen is *not* (?) available for symmetric (square) matrices?

For financial time-series (my main application) they would usually be symmetric, square, semi-positive definite matrices, thus complex values won't be an issue.

**Comment by cdeterman** [comment]
@erolbicero well that's embarrassing.  `eigen` is **now** available for symmetric, square matrices.

**Comment by erolbicero** [comment]
@cdeterman, no worries, I had a hunch it was a typo (was actually hoping it was) but just wanted to make sure.

That's great news, thanks.  So I can go ahead and install, and then run a Pearson cov and Eigen decomposition?

**Comment by cdeterman** [comment]
@erolbicero only `eigen` at the moment.  I am still experimenting with a few different implementations of the Pearson covariance.  But feel free to install and experiment (be good to verify it installs correctly).

**Comment by cdeterman** [comment]
The Pearson covariance is now available with the `cov` command, just like with base R matrix objects.

**Comment by cdeterman** [comment]
FYI, if running the new functions on NVIDIA GPU's the performance will be suboptimal (as gpuR used OpenCL).  I need to implement the CUDA based versions in gpuRcuda for improved performance.

**Comment by erolbicero** [comment]
thanks @cdeterman I haven't had a chance to try it out yet, I'll let you know once I do.
