### ISSUE TITLE
R crash with detectGPUs and bad platform ID

### ISSUE THREAD

**Issue by jackwasey** [cdeterman/gpuR#63]
```
gpuR::detectGPUs(7L)

 *** caught segfault ***
address 0x7f18e1000023, cause 'invalid permissions'

Traceback:
 1: .Call("gpuR_cpp_detectGPUs", PACKAGE = "gpuR", platform_idx)
 2: cpp_detectGPUs(platform_idx)
 3: doTryCatch(return(expr), name, parentenv, handler)
 4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5: tryCatchList(expr, classes, parentenv, handlers)
 6: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)  ...
 7: try(cpp_detectGPUs(platform_idx), silent = TRUE)
 8: gpuR::detectGPUs(7L)
```

R 3.3.2, Ubuntu 16.04, intel CPU/GPU, no other graphics.

I accept this may well be a problem in my set-up, but to trash my R session seems a little unfair.

**Comment by cdeterman** [comment]
Hi @jackwasey, I believe this is because you are passing `7L` to the function.  I highly doubt you have 7 OpenCL platforms on your machine.  I thought my `try` function would have handled that problem better but apparently not.  Try just running it with no arguments or with `1L`.  If you don't know how many platforms you have you can also run `detectPlatforms()`.  Also, listing the available contexts is also a useful view with `listContexts()`.

**Comment by jackwasey** [comment]
Hi - I agree seven was way too big, but I was not at that point sure whether each platform was numbered from zero or one. However, it killed my entire R process (not just an error), so regardless of the sanity of 7, I thought you'd want to know this.

**Comment by cdeterman** [comment]
@jackwasey I agree, thank you for reporting the problem.  I will label this as a bug and try to reproduce and fix it locally on my machine too.  That said, did changing the index solve the problem?  Does the function work for you?

**Comment by jackwasey** [comment]
Yes, it worked when the index was reasonable. Thanks.
