### ISSUE TITLE
How can I use gpuR package to create thread to reach the goal of parallel computing

### ISSUE THREAD

**Issue by XiaobaoZhu** [cdeterman/gpuR#88]
I want use gpuR package to parallel computing. So I want to use this package to create threads by myself. For example, I want create 1000 threads to inverse 1000 matrices at same time with GPU. Can I finish the work by gpuR?

**Comment by cdeterman** [comment]
Parallel GPU processing is part of issue #24.  Using something like `foreach` is dependent upon your number of CPUs.  Generally,  each GPU is mapped to a CPU and can be done as shown in the aforementioned issue.  If you have a machine with 1000 CPU's and 1000 GPUs then you can go wild but I doubt you have such a machine (that would be pretty sweet though).

However, when using the `vclMatrix` objects the calls are asynchronous meaning the cursor will return immediately after issue the command (processing continues in the background).  You can wait for all previous jobs to finish by calling `synchronize()` as of the current `develop` version.  If all your matrices and output matrices fit in the GPU RAM then it is my understanding that a GPU will try to process them all simultaneously (this may depend on the vendor).  You need to be careful with packages like this because the GPU RAM is only cleared following garbage collection so you may need to manage `gc` calls as well.  

The only way to find out is to try to write something and test it (probably on a smaller scale at first though).
